### ISSUE TITLE
JCM First Article Review 

### ISSUE THREAD

**Issue by puneet0191** [joomla-projects/gsoc16_menu-for-article#1]
#### Please prepare Draft Article for JCM Magazine

Get it reviewed from Mentor's, Submit it on JCM.

**Comment by shubhamnba2009** [comment]
I have submitted the article in article submission bucket at JCM site. Will be sharing the link when it will get published.

**Comment by pe7er** [comment]
Thanks @shubhamnba2009

**Comment by shubhamnba2009** [comment]
Just like this @gunjanpatel .
I have 3 more issues. As puneet told that we are going to use github issue tracking system to track milestones

**Comment by gunjanpatel** [comment]
Yes thanks @shubhamnba2009

**Comment by shubhamnba2009** [comment]
JCM article is ready and is processed for published. Therefore I am closing this issue.

**Comment by puneet0191** [comment]
Thanks :+1:  Nice work on this one

**Comment by pe7er** [comment]
Link to Joomla Community Magazine article: http://magazine.joomla.org/issues/issue-june-2016/item/3049-helping-out-yash-by-improving-joomla-menu-item-workflow
