### ISSUE TITLE
No menu item information in edit view

### ISSUE THREAD

**Issue by gunjanpatel** [joomla-projects/gsoc16_menu-for-article#10]
#### Steps to reproduce the issue
1. I have added article and created menu item as in workflow
2. I am going to edit the same article again, there is no information about menu item.

![edit-empty](https://cloud.githubusercontent.com/assets/2002921/16551823/facaa8c0-41d9-11e6-926a-1c197f919391.png)
#### Expected result

There should be loaded menu item information if created previously.

**Comment by gunjanpatel** [comment]
@pe7er please add your suggestions here that how edit view should be handled.

**Comment by pe7er** [comment]
I would use the item Title (here: "Cards") as default suggestion for Menu Title, e.g using JavaScript.

**Comment by shubhamnba2009** [comment]
But using javascript only article title and alias will get copied to menu title and alias whereas menu item and parent_id are not retrieved

**Comment by gunjanpatel** [comment]
You are getting it all wrong. You needs to get all the menu items suitable for menu item parent. (You are thinking about article parent item which is wrong). Try to check menu item view and see how they are generating dropdown for parent selection.

**Comment by pe7er** [comment]
The default "Menu Title" is now derived from the Article title.
Nice work!
