### ISSUE TITLE
Duplicate entry fatal error in article edit

### ISSUE THREAD

**Issue by gunjanpatel** [joomla-projects/gsoc16_menu-for-article#11]
#### Steps to reproduce the issue
1. Going to edit article with the same information. I only want to change article text and nothing else. Then it will create this duplicate content error.

![duplicate-entry](https://cloud.githubusercontent.com/assets/2002921/16551961/d52a872e-41da-11e6-812a-6be3946bae6d.png)
#### Expected result

Should not create new menu item and/or should update existing.
@pe7er please add your suggestions.

**Comment by shubhamnba2009** [comment]
I was not able to replicate this error..
1. Opened article edit view.
2. Changed article text and nothing else.
3. Successfull article save.

Before:
![before_article_edit](https://cloud.githubusercontent.com/assets/12000068/16697915/78b0fd24-4569-11e6-85df-a70a9b244042.png)

After:
![after_article_edit](https://cloud.githubusercontent.com/assets/12000068/16697926/7edad850-4569-11e6-931b-81e39e1702af.png)

**Comment by gunjanpatel** [comment]
1. Try to create menu item from article.
2. Try to edit the same article again, don't change anything just go to input and tab to alias. In this way you will have menu item auto filled.
3. Now try to save.

**Comment by pe7er** [comment]
I've reproduced this error via different a approach:
1. Create new article + create menu link + assign it to Main Menu
2. Change the Menu Link: change the "Menu name" to another menu.
3. Save will trigger the same error: 

```
An error has occurred.
 1062 Duplicate entry '0-0-test1-2-*' for key 'idx_client_id_parent_id_alias_language' SQL=INSERT INTO `#__menu` 

```

**Comment by pe7er** [comment]
Maybe you could disable the form on "Menu Link" tab when a menu item has been created?
I mean, list all Menu Title + Alias + Menu name + Parent Item without being able to change them.
And a "delete" or "edit" functionality in case the admin wants to change the link?

**Comment by pe7er** [comment]
Or could you add a hidden field "jform[menulink][id]" which is 0 for a new menu items,
or the menu item id when already selected?

**Comment by shubhamnba2009** [comment]
@pe7er Can you explain above comment again? "the menu item id when already selected?" part

**Comment by pe7er** [comment]
Yes, if you've saved an article with a link to menu item, then the menu item (and menu item ID) is known, isn't it?

If you add that menu item id (which is also known as "itemId") as hidden field to the create menu link form, you might probably prevent the duplicate entry error.

**Comment by shubhamnba2009** [comment]
The above commit solves this issue so I am closing this issue
