### ISSUE TITLE
Newly created menu item should be published by default

### ISSUE THREAD

**Issue by gunjanpatel** [joomla-projects/gsoc16_menu-for-article#12]
#### Steps to reproduce the issue

Created menu item from article and it is found unpublished by default.

![unpublished-menu-item](https://cloud.githubusercontent.com/assets/2002921/16552106/d95da140-41db-11e6-8b4f-52a18143f3d7.png)
#### Expected result

IMO this should be published by default.

**Comment by pe7er** [comment]
I was able to reproduce this error.

**Comment by pe7er** [comment]
The new menu item is now published by default. This issue seems to have been solved. 
Can we close this issue?
