### ISSUE TITLE
Not showing newly create menu item in frontend when I publish it

### ISSUE THREAD

**Issue by gunjanpatel** [joomla-projects/gsoc16_menu-for-article#14]
#### Steps to reproduce the issue
1. When I publish new menu item from menu item list view
2. No menu item showing in frontend.

![problem-in-new-menu-item](https://cloud.githubusercontent.com/assets/2002921/16552299/93853208-41dd-11e6-8cac-3f5c74abe07d.png)

_[Note: When I edit and save menu item from menu item edit view it start showing in frontend. But this should not be happen. You must able to see menu item when you just save it from article edit view.]_
#### Expected result

![problem-in-new-menu-item-frontend](https://cloud.githubusercontent.com/assets/2002921/16552339/df3174e6-41dd-11e6-8035-d74721c29aa9.png)

**Comment by shubhamnba2009** [comment]
I did not clearly Understood this issue gunjan... I mean after creating menu item from menu link tab the menu item must not come in the fornt-end immediately,... Are you referring to this?
According to your issue reproducing steps:
1. Clicking publish checkbox in before menu item in menu list view.
2. Going to frontend.
3. Menu comes in front end.
4. If again clicked on published checkbox(making unpublish), menu disappears from front end

So i think it is working properly.

**Comment by gunjanpatel** [comment]
Expected result is, when someone create menu item from article they should see it in frontend. 
Right now if you will try you will not able to see in frontend. 
Because of two reason:
1. It is unpublished by default
2. Some issue in creating menu item so if you publish it but still not see in frontend (You should try publish it from menu item listing page)

**Comment by pe7er** [comment]
I've tested this issue and it seems to have been solved.
