### ISSUE TITLE
Changing title in menu link tab in edit view results in error

### ISSUE THREAD

**Issue by shubhamnba2009** [joomla-projects/gsoc16_menu-for-article#16]
#### Steps to reproduce the issue
1. Create a new article.
2. Fill all the necessary details including menu link tab.
3. Save the article.
4. Open article again to edit.
5. Go to menu link option tab.
6. Change title only.
#### Expected result
1. The new title must be saved.
#### Actual result

![retrieve error](https://cloud.githubusercontent.com/assets/12000068/17040020/1238d1be-4fbb-11e6-987e-905091ae6649.png)

Also the information in menu table link column changes

**Comment by pe7er** [comment]
I can reproduce this error with the Alias field too.
And with changing the Menu, see #19

**Comment by gunjanpatel** [comment]
I can reproduce it and also my page is resulting into infinite look due to trigger calling it self in model save method.

**Comment by shubhamnba2009** [comment]
The above commit solves the bug
