### ISSUE TITLE
The Menu Title is not automatically suggested

### ISSUE THREAD

**Issue by pe7er** [joomla-projects/gsoc16_menu-for-article#17]
#### Steps to reproduce the issue
1. Create a new article, open [Menu link options],
   the Menu Title is empty.
2. Save an article or open an existing article, open [Menu link options],
   the Menu Title is empty.
#### Expected result

It would be nice if the Menu Title would be automatically suggested on basis of the article title.
#### Actual result

the Menu Title is empty.

**Comment by shubhamnba2009** [comment]
This enhancement is done through this commit: 3b65251e20238bdcf5f46cfec277797d1d6680aa

**Comment by shubhamnba2009** [comment]
I am closing this issue as the enhancement is done
