### ISSUE TITLE
Change "Menu link options > Menu name" = error

### ISSUE THREAD

**Issue by pe7er** [joomla-projects/gsoc16_menu-for-article#19]
#### Steps to reproduce the issue

Edit an existing article that has been assigned to a menu (so the fields in "Menu link options" all have some value),
change the Menu name to some other menu & save 
#### Expected result

I would expect that the newly assigned menu would be created 
(though I am not sure what should happen with the previous assigned menu item)
#### Actual result

A page full of errors like:
Notice: Undefined index: menuordering in [..]/administrator/components/com_menus/models/item.php on line 1294
and all "Menu link options" fields are empty again.

**Comment by shubhamnba2009** [comment]
The above commit solves the bug.
