### ISSUE TITLE
Sorry, this project is no use anymore

### ISSUE THREAD

**Issue by infograf768** [joomla-projects/gsoc16_menu-for-article#21]
As we implemented in the GSOC multilingual project what we needed concerning menu modals, we now have a PR toward 3.7.0 (where the modal_menu new field is already merged) with the new editor-xtd

See https://github.com/joomla/joomla-cms/pull/11721

**Comment by infograf768** [comment]
Forget it: my mistake.

**Comment by gunjanpatel** [comment]
np. Thank you for looking into it.
