### ISSUE TITLE
Linking article with menu of single article view without necessary fields.

### ISSUE THREAD

**Issue by shubhamnba2009** [joomla-projects/gsoc16_menu-for-article#5]
- [x] Adding new tab "Menu Link" in article edit view
- [x] Adding basic field such as "Menu title" under Menu Link tab without database connectivity.
- [x] Addind database connectivity

**Comment by shubhamnba2009** [comment]
@gunjanpatel I was unable to add you under the assignee list. It is not listing you. Therefore i m mentioning you in comment.

**Comment by puneet0191** [comment]
@javigomez  Can you please add @gunjanpatel to the team :)

**Comment by gunjanpatel** [comment]
Thanks @shubhamnba2009 I will love to see your changes in Pull Request. You will able to update your PR later so it will be fine if you send changes in PR and keep updating it. In this way we will able to see the code and will also able suggest if any changes needed in code.

**Comment by javigomez** [comment]
Gunjan is now added to the team.

**Comment by gunjanpatel** [comment]
Thanks @javigomez
