### ISSUE TITLE
Going through different methods to make the menu item workflow functionality generic.

### ISSUE THREAD

**Issue by shubhamnba2009** [joomla-projects/gsoc16_menu-for-article#9]
- [x] Go through helper function method.
- [x] Go through plugin method
- [x] Check if there is another suitable method

**Comment by gunjanpatel** [comment]
@shubhamnba2009  Can you provide the status of this task?

**Comment by shubhamnba2009** [comment]
I have gone through helper and plugin method...Comparing both methods to find which is suitable...

**Comment by gunjanpatel** [comment]
Please also provide what you have found and conclusion, what is your choice and why etc... :smile:

**Comment by shubhamnba2009** [comment]
Yeah sure :)
When I was going through Plugin method..I had a doubt that how the information required for the menu table can be made out from any edit view using plugin...  After that I found that plugin can be called because of its trigger functionality, automatically whenever any edit view is opened. 
But if helper function is made i have to code separately in every edit view to call this helper function i.e. where I want to use it. If there is a third party component he have to code inside it to use the helper function whereas in plugin case. No need of extra coding..
This is what I have found out

**Comment by gunjanpatel** [comment]
So what is your conclusion and what you are going to develop this week?

**Comment by shubhamnba2009** [comment]
I am more inclined towards using plugin method.. Rest I'll discuss with you in today's meeting.. Should we discuss here or in the meeting?

**Comment by gunjanpatel** [comment]
Ok we will discuss in meeting. np.

**Comment by pe7er** [comment]
We have discussed about this issue last meeting. Can we close this issue?

**Comment by shubhamnba2009** [comment]
@gunjanpatel @pe7er I am closing this issue since we have already discussed and decided to move into which direction :)
